<<<<<<< HEAD
# Do not modify this file!  It was generated by 
=======
# Do not modify this file!  It was generated by ‘nixos-generate-config’
>>>>>>> fix-sshfs-commit
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
<<<<<<< HEAD
 imports =
   [ (modulesPath + "/installer/scan/not-detected.nix")
   ];

 boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" "sd_mod" ];
 boot.initrd.kernelModules = [ ];
 boot.kernelModules = [ "kvm-amd" ];
 boot.extraModulePackages = [ ];

 fileSystems."/" =
   { device = "/dev/disk/by-uuid/4b3805bf-8189-46b2-8320-f944f46089ea";
     fsType = "ext4";
   };

 fileSystems."/boot" =
   { device = "/dev/disk/by-uuid/EC4F-269E";
     fsType = "vfat";
   };

 swapDevices = [ ];

 # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
 # (the default) this is the recommended approach. When using systemd-networkd it's
 # still possible to use this option, but it's recommended to use it in conjunction
 # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
 networking.useDHCP = lib.mkDefault true;
 # networking.interfaces.enp16s0.useDHCP = lib.mkDefault true;
 # networking.interfaces.wlp17s0.useDHCP = lib.mkDefault true;

 nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
 hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
=======
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/74cd3dc4-d623-44f1-ac18-d938770155a6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/08FB-D26B";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp16s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp17s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
>>>>>>> fix-sshfs-commit
}
